"""empty message

Revision ID: 704ec61826e9
Revises: 1724d8ca3a7d
Create Date: 2020-03-27 23:03:25.010019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704ec61826e9'
down_revision = '1724d8ca3a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('fk_task_user_id_user'), 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_user_id_user'), 'task', type_='foreignkey')
    op.alter_column('task', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
